import db from 'better-sqlite3';

import RepositoryService from './repository.service';

import EngineRepository from '../repository/config/engine.repository';
import IpFilterRepository from '../repository/config/ip-filter.repository';
import ScanModeRepository from '../repository/config/scan-mode.repository';
import SouthConnectorRepository from '../repository/config/south-connector.repository';
import NorthConnectorRepository from '../repository/config/north-connector.repository';
import LogRepository from '../repository/logs/log.repository';
import HistoryQueryRepository from '../repository/config/history-query.repository';
import UserRepository from '../repository/config/user.repository';
import CryptoRepository from '../repository/crypto/crypto.repository';
import SouthConnectorMetricsRepository from '../repository/logs/south-connector-metrics.repository';
import EngineMetricsRepository from '../repository/logs/engine-metrics.repository';
import SouthCacheRepository from '../repository/cache/south-cache.repository';
import NorthConnectorMetricsRepository from '../repository/logs/north-connector-metrics.repository';
import CertificateRepository from '../repository/config/certificate.repository';
import OianalyticsRegistrationRepository from '../repository/config/oianalytics-registration.repository';
import OianalyticsCommandRepository from '../repository/config/oianalytics-command.repository';
import OianalyticsMessageRepository from '../repository/config/oianalytics-message.repository';

jest.mock('better-sqlite3', () => jest.fn(() => 'sqlite database'));
jest.mock('../repository/crypto/crypto.repository');
jest.mock('../repository/config/ip-filter.repository');
jest.mock('../repository/config/scan-mode.repository');
jest.mock('../repository/config/engine.repository');
jest.mock('../repository/config/north-connector.repository');
jest.mock('../repository/logs/north-connector-metrics.repository');
jest.mock('../repository/config/south-connector.repository');
jest.mock('../repository/cache/south-cache.repository');
jest.mock('../repository/logs/south-connector-metrics.repository');
jest.mock('../repository/logs/engine-metrics.repository');
jest.mock('../repository/logs/log.repository');
jest.mock('../repository/config/history-query.repository');
jest.mock('../repository/config/user.repository');
jest.mock('../repository/config/certificate.repository');
jest.mock('../repository/config/oianalytics-registration.repository');
jest.mock('../repository/config/oianalytics-command.repository');
jest.mock('../repository/config/oianalytics-message.repository');

describe('Repository service', () => {
  it('should properly initialize service', () => {
    const repositoryService = new RepositoryService('myConfigDatabase', 'myLogDatabase', 'myCryptoDatabase', 'myCacheDatabase');
    expect(db).toHaveBeenCalledWith('myConfigDatabase');
    expect(db).toHaveBeenCalledWith('myLogDatabase');
    expect(db).toHaveBeenCalledWith('myCryptoDatabase');
    expect(db).toHaveBeenCalledWith('myCacheDatabase');
    expect(EngineRepository).toHaveBeenCalledWith('sqlite database');
    expect(CryptoRepository).toHaveBeenCalledWith('sqlite database');
    expect(IpFilterRepository).toHaveBeenCalledWith('sqlite database');
    expect(ScanModeRepository).toHaveBeenCalledWith('sqlite database');
    expect(NorthConnectorRepository).toHaveBeenCalledWith('sqlite database');
    expect(NorthConnectorMetricsRepository).toHaveBeenCalledWith('sqlite database');
    expect(SouthConnectorRepository).toHaveBeenCalledWith('sqlite database');
    expect(SouthConnectorMetricsRepository).toHaveBeenCalledWith('sqlite database');
    expect(EngineMetricsRepository).toHaveBeenCalledWith('sqlite database');
    expect(SouthCacheRepository).toHaveBeenCalledWith('sqlite database');
    expect(LogRepository).toHaveBeenCalledWith('sqlite database');
    expect(HistoryQueryRepository).toHaveBeenCalledWith('sqlite database');
    expect(UserRepository).toHaveBeenCalledWith('sqlite database');
    expect(OianalyticsRegistrationRepository).toHaveBeenCalledWith('sqlite database');
    expect(CertificateRepository).toHaveBeenCalledWith('sqlite database');
    expect(OianalyticsCommandRepository).toHaveBeenCalledWith('sqlite database');
    expect(OianalyticsMessageRepository).toHaveBeenCalledWith('sqlite database');

    expect(repositoryService.engineRepository).toBeDefined();
    expect(repositoryService.cryptoRepository).toBeDefined();
    expect(repositoryService.ipFilterRepository).toBeDefined();
    expect(repositoryService.scanModeRepository).toBeDefined();
    expect(repositoryService.northConnectorRepository).toBeDefined();
    expect(repositoryService.northMetricsRepository).toBeDefined();
    expect(repositoryService.southConnectorRepository).toBeDefined();
    expect(repositoryService.southMetricsRepository).toBeDefined();
    expect(repositoryService.engineMetricsRepository).toBeDefined();
    expect(repositoryService.oianalyticsRegistrationRepository).toBeDefined();
    expect(repositoryService.southCacheRepository).toBeDefined();
    expect(repositoryService.logRepository).toBeDefined();
    expect(repositoryService.historyQueryRepository).toBeDefined();
    expect(repositoryService.userRepository).toBeDefined();
    expect(repositoryService.certificateRepository).toBeDefined();
    expect(repositoryService.oianalyticsCommandRepository).toBeDefined();
    expect(repositoryService.oianalyticsMessageRepository).toBeDefined();
  });
});
