export default {
  name: 'RestApi',
  category: 'api',
  description: 'REST description',
  modes: {
    subscription: false,
    lastPoint: false,
    lastFile: false,
    historyPoint: false,
    historyFile: true,
  },
  settings: [
    {
      key: 'url',
      type: 'OibText',
      label: 'URL',
      defaultValue: 'http://localhost',
      newRow: true,
      validators: ['required', ['pattern', '^http.*'], ['pattern', '^opc.tcp.*']],
      readDisplay: true,
    },
    {
      key: 'port',
      type: 'OibNumber',
      label: 'Port',
      defaultValue: 80,
      newRow: false,
      validators: ['required', ['min', 1], ['max', 65535]],
    },
    {
      key: 'requestMethod',
      type: 'OibSelect',
      options: ['GET', 'POST', 'PUT', 'PATCH'],
      label: 'HTTP Method',
      defaultValue: 'GET',
      newRow: false,
      validators: ['required'],
    },
    {
      key: 'authentication',
      type: 'OibAuthentication',
      label: 'Authentication',
      newRow: true,
    },
    {
      key: 'acceptSelfSigned',
      type: 'OibCheckbox',
      label: 'Accept rejected certificates?',
      defaultValue: false,
      newRow: false,
      class: 'col-2',
    },
    {
      key: 'connectionTimeout',
      type: 'OibNumber',
      label: 'Connection timeout (ms)',
      defaultValue: 1000,
      newRow: true,
      class: 'col-2',
      validators: ['required', ['min', 100], ['max', 30000]],
    },
  ],
  items: [
    {
      key: 'scanMode',
      type: 'OibScanMode',
      label: 'Scan mode',
      newRow: true,
      validators: ['required'],
    },
    {
      key: 'requestTimeout',
      type: 'OibNumber',
      label: 'Request timeout (ms)',
      defaultValue: 1000,
      newRow: false,
      class: 'col-2',
      validators: ['required', ['min', 100], ['max', 60000]],
    },
    {
      key: 'maxReadInterval',
      type: 'OibNumber',
      label: 'Max read interval (s)',
      defaultValue: 0,
      newRow: true,
      class: 'col-2',
      validators: ['required'],
    },
    {
      key: 'readIntervalDelay',
      type: 'OibNumber',
      label: 'Read interval delay (ms)',
      defaultValue: 200,
      newRow: false,
      class: 'col-2',
      validators: ['required', ['min', 100], ['max', 3_600_000]],
    },
    {
      key: 'queryParams',
      type: 'OibTable',
      rows: {
        queryParamKey: {
          type: 'OibText',
          label: 'Key',
          defaultValue: '',
        },
        queryParamValue: {
          type: 'OibText',
          label: 'Value',
          defaultValue: '',
        },
      },
    },
    {
      key: 'body',
      type: 'OibCodeBlock',
      label: 'Body',
      contentType: 'json',
      defaultValue: '',
      newRow: false,
    },
    {
      key: 'variableDateFormat',
      type: 'OibSelect',
      label: 'Variable Date Format',
      options: ['ISO', 'number'],
      defaultValue: 'ISO',
      newRow: true,
    },
    {
      key: 'payloadParser',
      type: 'OibSelect',
      label: 'Payload parser',
      options: ['Raw', 'OIAnalytics time values', 'SLIMS'],
      defaultValue: 'Raw',
      newRow: true,
      validators: ['required'],
    },
    {
      key: 'convertToCsv',
      type: 'OibCheckbox',
      label: 'Convert payload into CSV?',
      defaultValue: true,
      newRow: true,
      validators: ['required'],
    },
    {
      key: 'delimiter',
      type: 'OibSelect',
      options: [',', ';', '|'],
      label: 'Delimiter',
      defaultValue: ',',
      newRow: false,
      validators: ['required'],
    },
    {
      key: 'filename',
      type: 'OibText',
      label: 'Filename',
      defaultValue: '@ConnectorName-results_@CurrentDate-@QueryPart.csv',
      validators: ['required'],
    },
    {
      key: 'compression',
      type: 'OibCheckbox',
      label: 'Compress File?',
      defaultValue: false,
      newRow: false,
      validators: ['required'],
    },
  ],
}
