// DO NOT EDIT THIS BY HAND!
// This file is auto-generated by the script located backend/src/settings-interface.generator.ts
// To update the typescript model run npm run generate-settings-interface on the backend project

export const NORTH_AZURE_BLOB_SETTINGS_AUTHENTICATIONS = ['access-key', 'sas-token', 'aad', 'external'] as const;
export type NorthAzureBlobSettingsAuthentication = (typeof NORTH_AZURE_BLOB_SETTINGS_AUTHENTICATIONS)[number];

export const NORTH_O_I_ANALYTICS_SETTINGS_SPECIFIC_SETTINGS_AUTHENTICATIONS = ['basic', 'aad-client-secret', 'aad-certificate'] as const;
export type NorthOIAnalyticsSettingsSpecificSettingsAuthentication =
  (typeof NORTH_O_I_ANALYTICS_SETTINGS_SPECIFIC_SETTINGS_AUTHENTICATIONS)[number];

export const NORTH_S_F_T_P_SETTINGS_AUTHENTICATIONS = ['password', 'private-key'] as const;
export type NorthSFTPSettingsAuthentication = (typeof NORTH_S_F_T_P_SETTINGS_AUTHENTICATIONS)[number];

export interface NorthOIAnalyticsSettingsSpecificSettings {
  host: string;
  acceptUnauthorized: boolean;
  authentication: NorthOIAnalyticsSettingsSpecificSettingsAuthentication;
  accessKey?: string;
  secretKey?: string | null;
  tenantId?: string | null;
  clientId?: string;
  clientSecret?: string | null;
  certificateId?: string | null;
  scope?: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthAmazonS3Settings {
  bucket: string;
  region: string;
  folder: string;
  accessKey: string;
  secretKey: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthAzureBlobSettings {
  useADLS: boolean;
  useCustomUrl: boolean;
  account?: string;
  customUrl?: string;
  container: string;
  path: string | null;
  authentication: NorthAzureBlobSettingsAuthentication;
  sasToken?: string | null;
  accessKey?: string | null;
  tenantId?: string | null;
  clientId?: string | null;
  clientSecret?: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthConsoleSettings {
  verbose: boolean;
}

export interface NorthFileWriterSettings {
  outputFolder: string;
  prefix: string | null;
  suffix: string | null;
}

export interface NorthOIAnalyticsSettings {
  useOiaModule: boolean;
  timeout: number;
  compress: boolean;
  specificSettings?: NorthOIAnalyticsSettingsSpecificSettings | null;
}

export interface NorthSFTPSettings {
  host: string;
  port: number;
  authentication: NorthSFTPSettingsAuthentication;
  username: string | null;
  password?: string | null;
  privateKey?: string;
  passphrase?: string | null;
  remoteFolder: string;
  prefix: string | null;
  suffix: string | null;
}

export type NorthSettings =
  | NorthAmazonS3Settings
  | NorthAzureBlobSettings
  | NorthConsoleSettings
  | NorthFileWriterSettings
  | NorthOIAnalyticsSettings
  | NorthSFTPSettings;
