// DO NOT EDIT THIS BY HAND!
// This file is auto-generated by the script located backend/src/settings-interface.generator.ts
// To update the typescript model run npm run generate-settings-interface on the backend project

import { Timezone } from './types';

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsDatetimeSettingsInputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsInputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATA_TYPES = ['string', 'number', 'boolean', 'datetime'] as const;
export type TransformerCsvToMqttSettingsObjectFieldsDataType = (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATA_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerCsvToMqttSettingsDelimiter = (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_PAYLOAD_TYPES = ['string', 'number', 'boolean', 'datetime', 'object'] as const;
export type TransformerCsvToMqttSettingsPayloadType = (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_PAYLOAD_TYPES)[number];

export const TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_TIMESTAMP_SETTINGS_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToTimeValuesSettingsTimestampSettingsType =
  (typeof TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_TIMESTAMP_SETTINGS_TYPES)[number];

export const TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerCsvToTimeValuesSettingsDelimiter = (typeof TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToCsvSettingsFieldsDatetimeSettingsInputType =
  (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToCsvSettingsFieldsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATA_TYPES = ['string', 'number', 'datetime', 'array', 'boolean', 'object'] as const;
export type TransformerJsonToCsvSettingsFieldsDataType = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATA_TYPES)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerJsonToCsvSettingsDelimiter = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_JSON_TO_MQTT_SETTINGS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToMqttSettingsDatetimeSettingsInputType =
  (typeof TRANSFORMER_JSON_TO_MQTT_SETTINGS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_MQTT_SETTINGS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToMqttSettingsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_JSON_TO_MQTT_SETTINGS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToMqttSettingsObjectFieldsDatetimeSettingsInputType =
  (typeof TRANSFORMER_JSON_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToMqttSettingsObjectFieldsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_JSON_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATA_TYPES = ['string', 'number', 'boolean', 'datetime'] as const;
export type TransformerJsonToMqttSettingsObjectFieldsDataType = (typeof TRANSFORMER_JSON_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATA_TYPES)[number];

export const TRANSFORMER_JSON_TO_MQTT_SETTINGS_PAYLOAD_TYPES = ['string', 'number', 'boolean', 'datetime', 'object'] as const;
export type TransformerJsonToMqttSettingsPayloadType = (typeof TRANSFORMER_JSON_TO_MQTT_SETTINGS_PAYLOAD_TYPES)[number];

export const TRANSFORMER_JSON_TO_TIME_VALUES_SETTINGS_TIMESTAMP_SETTINGS_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToTimeValuesSettingsTimestampSettingsType =
  (typeof TRANSFORMER_JSON_TO_TIME_VALUES_SETTINGS_TIMESTAMP_SETTINGS_TYPES)[number];

export const TRANSFORMER_SETPOINT_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES = ['coil', 'register'] as const;
export type TransformerSetpointToModbusSettingsMappingModbusType =
  (typeof TRANSFORMER_SETPOINT_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerTimeValuesToCsvSettingsDelimiter = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_TIMESTAMP_TYPES = ['string', 'iso-string', 'unix-epoch', 'unix-epoch-ms'] as const;
export type TransformerTimeValuesToCsvSettingsTimestampType = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_TIMESTAMP_TYPES)[number];

export const TRANSFORMER_TIME_VALUES_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES = ['coil', 'register'] as const;
export type TransformerTimeValuesToModbusSettingsMappingModbusType =
  (typeof TRANSFORMER_TIME_VALUES_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES)[number];

export const TRANSFORMER_TIME_VALUES_TO_OIANALYTICS_SETTINGS_PRECISIONS = ['ms', 's', 'min', 'hr'] as const;
export type TransformerTimeValuesToOianalyticsSettingsPrecision =
  (typeof TRANSFORMER_TIME_VALUES_TO_OIANALYTICS_SETTINGS_PRECISIONS)[number];

export interface TransformerCsvToMqttSettingsDatetimeSettings {
  inputType: TransformerCsvToMqttSettingsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerCsvToMqttSettingsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerCsvToMqttSettingsObjectFieldsDatetimeSettings {
  inputType: TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerCsvToMqttSettingsObjectFields {
  key: string;
  column: string;
  dataType: TransformerCsvToMqttSettingsObjectFieldsDataType;
  datetimeSettings?: TransformerCsvToMqttSettingsObjectFieldsDatetimeSettings | null;
}

export interface TransformerCsvToTimeValuesSettingsTimestampSettings {
  type: TransformerCsvToTimeValuesSettingsTimestampSettingsType;
  timezone?: Timezone;
  format?: string;
  locale?: string;
}

export interface TransformerJsonToCsvSettingsFieldsDatetimeSettings {
  inputType: TransformerJsonToCsvSettingsFieldsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerJsonToCsvSettingsFieldsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerJsonToCsvSettingsFields {
  columnName: string;
  jsonPath: string;
  dataType: TransformerJsonToCsvSettingsFieldsDataType;
  datetimeSettings?: TransformerJsonToCsvSettingsFieldsDatetimeSettings | null;
}

export interface TransformerJsonToMqttSettingsDatetimeSettings {
  inputType: TransformerJsonToMqttSettingsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerJsonToMqttSettingsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerJsonToMqttSettingsObjectFieldsDatetimeSettings {
  inputType: TransformerJsonToMqttSettingsObjectFieldsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerJsonToMqttSettingsObjectFieldsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerJsonToMqttSettingsObjectFields {
  key: string;
  path: string;
  dataType: TransformerJsonToMqttSettingsObjectFieldsDataType;
  datetimeSettings?: TransformerJsonToMqttSettingsObjectFieldsDatetimeSettings | null;
}

export interface TransformerJsonToTimeValuesSettingsTimestampSettings {
  type: TransformerJsonToTimeValuesSettingsTimestampSettingsType;
  timezone?: Timezone;
  format?: string;
  locale?: string;
}

export interface TransformerSetpointToModbusSettingsMapping {
  reference: string;
  address: string;
  modbusType: TransformerSetpointToModbusSettingsMappingModbusType;
}

export interface TransformerSetpointToMqttSettingsMapping {
  reference: string;
  topic: string;
}

export interface TransformerSetpointToOpcuaSettingsMapping {
  reference: string;
  nodeId: string;
}

export interface TransformerTimeValuesToModbusSettingsMapping {
  pointId: string;
  address: string;
  modbusType: TransformerTimeValuesToModbusSettingsMappingModbusType;
}

export interface TransformerTimeValuesToMqttSettingsMapping {
  pointId: string;
  topic: string;
}

export interface TransformerTimeValuesToOpcuaSettingsMapping {
  pointId: string;
  nodeId: string;
}

export interface TransformerCsvToMqttSettings {
  delimiter: TransformerCsvToMqttSettingsDelimiter;
  hasHeader: boolean;
  topicColumn: string;
  payloadType: TransformerCsvToMqttSettingsPayloadType;
  valueColumn?: string | null;
  datetimeSettings?: TransformerCsvToMqttSettingsDatetimeSettings | null;
  objectFields?: Array<TransformerCsvToMqttSettingsObjectFields> | null;
}

export interface TransformerCsvToTimeValuesSettings {
  delimiter: TransformerCsvToTimeValuesSettingsDelimiter;
  hasHeader: boolean;
  pointIdColumn: string;
  timestampColumn: string;
  valueColumn: string;
  timestampSettings: TransformerCsvToTimeValuesSettingsTimestampSettings | null;
}

export interface TransformerJsonToCsvSettings {
  filename: string;
  delimiter: TransformerJsonToCsvSettingsDelimiter;
  rowIteratorPath: string;
  fields: Array<TransformerJsonToCsvSettingsFields> | null;
}

export interface TransformerJsonToMqttSettings {
  rowIteratorPath: string;
  topicPath: string;
  payloadType: TransformerJsonToMqttSettingsPayloadType;
  valuePath?: string | null;
  datetimeSettings?: TransformerJsonToMqttSettingsDatetimeSettings | null;
  objectFields?: Array<TransformerJsonToMqttSettingsObjectFields> | null;
}

export interface TransformerJsonToTimeValuesSettings {
  rowIteratorPath: string;
  pointIdPath: string;
  timestampPath: string;
  valuePath: string;
  timestampSettings: TransformerJsonToTimeValuesSettingsTimestampSettings | null;
}

export type TransformerIgnoreSettings = object;

export type TransformerIsoSettings = object;

export interface TransformerSetpointToModbusSettings {
  mapping: Array<TransformerSetpointToModbusSettingsMapping> | null;
}

export interface TransformerSetpointToMqttSettings {
  mapping: Array<TransformerSetpointToMqttSettingsMapping> | null;
}

export interface TransformerSetpointToOpcuaSettings {
  mapping: Array<TransformerSetpointToOpcuaSettingsMapping> | null;
}

export interface TransformerTimeValuesToCsvSettings {
  filename: string;
  delimiter: TransformerTimeValuesToCsvSettingsDelimiter;
  pointIdColumnTitle: string;
  valueColumnTitle: string;
  timestampColumnTitle: string;
  timestampType: TransformerTimeValuesToCsvSettingsTimestampType;
  timestampFormat?: string;
  timezone?: Timezone;
}

export type TransformerTimeValuesToJsonSettings = object;

export interface TransformerTimeValuesToModbusSettings {
  mapping: Array<TransformerTimeValuesToModbusSettingsMapping> | null;
}

export interface TransformerTimeValuesToMqttSettings {
  mapping: Array<TransformerTimeValuesToMqttSettingsMapping> | null;
}

export interface TransformerTimeValuesToOianalyticsSettings {
  precision: TransformerTimeValuesToOianalyticsSettingsPrecision;
}

export interface TransformerTimeValuesToOpcuaSettings {
  mapping: Array<TransformerTimeValuesToOpcuaSettingsMapping> | null;
}

export type TransformerSettings =
  | TransformerCsvToMqttSettings
  | TransformerCsvToTimeValuesSettings
  | TransformerJsonToCsvSettings
  | TransformerJsonToMqttSettings
  | TransformerJsonToTimeValuesSettings
  | TransformerIgnoreSettings
  | TransformerIsoSettings
  | TransformerSetpointToModbusSettings
  | TransformerSetpointToMqttSettings
  | TransformerSetpointToOpcuaSettings
  | TransformerTimeValuesToCsvSettings
  | TransformerTimeValuesToJsonSettings
  | TransformerTimeValuesToModbusSettings
  | TransformerTimeValuesToMqttSettings
  | TransformerTimeValuesToOianalyticsSettings
  | TransformerTimeValuesToOpcuaSettings;
