// DO NOT EDIT THIS BY HAND!
// This file is auto-generated by the script located backend/src/settings-interface.generator.ts
// To update the typescript model run npm run generate-settings-interface on the backend project

import { Timezone } from './types';

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsDatetimeSettingsInputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsInputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATA_TYPES = ['string', 'number', 'boolean', 'datetime'] as const;
export type TransformerCsvToMqttSettingsObjectFieldsDataType = (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_OBJECT_FIELDS_DATA_TYPES)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerCsvToMqttSettingsDelimiter = (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_CSV_TO_MQTT_SETTINGS_PAYLOAD_TYPES = ['string', 'number', 'boolean', 'datetime', 'object'] as const;
export type TransformerCsvToMqttSettingsPayloadType = (typeof TRANSFORMER_CSV_TO_MQTT_SETTINGS_PAYLOAD_TYPES)[number];

export const TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_TIMESTAMP_SETTINGS_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerCsvToTimeValuesSettingsTimestampSettingsType =
  (typeof TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_TIMESTAMP_SETTINGS_TYPES)[number];

export const TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerCsvToTimeValuesSettingsDelimiter = (typeof TRANSFORMER_CSV_TO_TIME_VALUES_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_INPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToCsvSettingsFieldsDatetimeSettingsInputType =
  (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_INPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES = [
  'iso-string',
  'unix-epoch',
  'unix-epoch-ms',
  'string'
] as const;
export type TransformerJsonToCsvSettingsFieldsDatetimeSettingsOutputType =
  (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATETIME_SETTINGS_OUTPUT_TYPES)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATA_TYPES = ['string', 'number', 'datetime', 'array', 'boolean', 'object'] as const;
export type TransformerJsonToCsvSettingsFieldsDataType = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_FIELDS_DATA_TYPES)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_ENCODINGS = ['UTF_8', 'UTF_8_BOM', 'LATIN_1', 'UTF_16_LE'] as const;
export type TransformerJsonToCsvSettingsEncoding = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_ENCODINGS)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerJsonToCsvSettingsDelimiter = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_NEWLINES = ['CRLF', 'LF', 'CR'] as const;
export type TransformerJsonToCsvSettingsNewline = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_NEWLINES)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_QUOTE_CHARS = ['DOUBLE_QUOTE', 'SINGLE_QUOTE', 'NONE'] as const;
export type TransformerJsonToCsvSettingsQuoteChar = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_QUOTE_CHARS)[number];

export const TRANSFORMER_JSON_TO_CSV_SETTINGS_ESCAPE_CHARS = ['BACKSLASH', 'DOUBLE_QUOTE'] as const;
export type TransformerJsonToCsvSettingsEscapeChar = (typeof TRANSFORMER_JSON_TO_CSV_SETTINGS_ESCAPE_CHARS)[number];

export const TRANSFORMER_SETPOINT_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES = ['coil', 'register'] as const;
export type TransformerSetpointToModbusSettingsMappingModbusType =
  (typeof TRANSFORMER_SETPOINT_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_ENCODINGS = ['UTF_8', 'UTF_8_BOM', 'LATIN_1', 'UTF_16_LE'] as const;
export type TransformerTimeValuesToCsvSettingsEncoding = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_ENCODINGS)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_DELIMITERS = [
  'DOT',
  'SEMI_COLON',
  'COLON',
  'COMMA',
  'NON_BREAKING_SPACE',
  'SLASH',
  'TAB',
  'PIPE'
] as const;
export type TransformerTimeValuesToCsvSettingsDelimiter = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_DELIMITERS)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_NEWLINES = ['CRLF', 'LF', 'CR'] as const;
export type TransformerTimeValuesToCsvSettingsNewline = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_NEWLINES)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_QUOTE_CHARS = ['DOUBLE_QUOTE', 'SINGLE_QUOTE', 'NONE'] as const;
export type TransformerTimeValuesToCsvSettingsQuoteChar = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_QUOTE_CHARS)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_ESCAPE_CHARS = ['BACKSLASH', 'DOUBLE_QUOTE'] as const;
export type TransformerTimeValuesToCsvSettingsEscapeChar = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_ESCAPE_CHARS)[number];

export const TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_TIMESTAMP_TYPES = ['string', 'iso-string', 'unix-epoch', 'unix-epoch-ms'] as const;
export type TransformerTimeValuesToCsvSettingsTimestampType = (typeof TRANSFORMER_TIME_VALUES_TO_CSV_SETTINGS_TIMESTAMP_TYPES)[number];

export const TRANSFORMER_TIME_VALUES_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES = ['coil', 'register'] as const;
export type TransformerTimeValuesToModbusSettingsMappingModbusType =
  (typeof TRANSFORMER_TIME_VALUES_TO_MODBUS_SETTINGS_MAPPING_MODBUS_TYPES)[number];

export const TRANSFORMER_TIME_VALUES_TO_OIANALYTICS_SETTINGS_PRECISIONS = ['ms', 's', 'min', 'hr'] as const;
export type TransformerTimeValuesToOianalyticsSettingsPrecision =
  (typeof TRANSFORMER_TIME_VALUES_TO_OIANALYTICS_SETTINGS_PRECISIONS)[number];

export interface TransformerCsvToMqttSettingsDatetimeSettings {
  inputType: TransformerCsvToMqttSettingsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerCsvToMqttSettingsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerCsvToMqttSettingsObjectFieldsDatetimeSettings {
  inputType: TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerCsvToMqttSettingsObjectFieldsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerCsvToMqttSettingsObjectFields {
  key: string;
  column: string;
  dataType: TransformerCsvToMqttSettingsObjectFieldsDataType;
  datetimeSettings?: TransformerCsvToMqttSettingsObjectFieldsDatetimeSettings | null;
}

export interface TransformerCsvToTimeValuesSettingsTimestampSettings {
  type: TransformerCsvToTimeValuesSettingsTimestampSettingsType;
  timezone?: Timezone;
  format?: string;
  locale?: string;
}

export interface TransformerJsonToCsvSettingsFieldsDatetimeSettings {
  inputType: TransformerJsonToCsvSettingsFieldsDatetimeSettingsInputType;
  inputTimezone?: Timezone;
  inputFormat?: string;
  inputLocale?: string;
  outputType: TransformerJsonToCsvSettingsFieldsDatetimeSettingsOutputType;
  outputTimezone?: Timezone;
  outputFormat?: string;
  outputLocale?: string;
}

export interface TransformerJsonToCsvSettingsFields {
  columnName: string;
  jsonPath: string;
  dataType: TransformerJsonToCsvSettingsFieldsDataType;
  fieldProcess?: string | null;
  datetimeSettings?: TransformerJsonToCsvSettingsFieldsDatetimeSettings | null;
}

export interface TransformerSetpointToModbusSettingsMapping {
  reference: string;
  address: string;
  modbusType: TransformerSetpointToModbusSettingsMappingModbusType;
}

export interface TransformerSetpointToMqttSettingsMapping {
  reference: string;
  topic: string;
}

export interface TransformerSetpointToOpcuaSettingsMapping {
  reference: string;
  nodeId: string;
}

export interface TransformerTimeValuesToModbusSettingsMapping {
  pointId: string;
  address: string;
  modbusType: TransformerTimeValuesToModbusSettingsMappingModbusType;
}

export interface TransformerTimeValuesToMqttSettingsMapping {
  pointId: string;
  topic: string;
}

export interface TransformerTimeValuesToOpcuaSettingsMapping {
  pointId: string;
  nodeId: string;
}

export interface TransformerCsvToMqttSettings {
  delimiter: TransformerCsvToMqttSettingsDelimiter;
  hasHeader: boolean;
  topicColumn: string;
  payloadType: TransformerCsvToMqttSettingsPayloadType;
  valueColumn?: string | null;
  datetimeSettings?: TransformerCsvToMqttSettingsDatetimeSettings | null;
  objectFields?: Array<TransformerCsvToMqttSettingsObjectFields> | null;
}

export interface TransformerCsvToTimeValuesSettings {
  delimiter: TransformerCsvToTimeValuesSettingsDelimiter;
  hasHeader: boolean;
  pointIdColumn: string;
  timestampColumn: string;
  valueColumn: string;
  timestampSettings: TransformerCsvToTimeValuesSettingsTimestampSettings;
}

export interface TransformerJsonToCsvSettings {
  filename: string;
  encoding: TransformerJsonToCsvSettingsEncoding;
  header: boolean | null;
  delimiter: TransformerJsonToCsvSettingsDelimiter;
  newline: TransformerJsonToCsvSettingsNewline;
  quoteChar: TransformerJsonToCsvSettingsQuoteChar;
  escapeChar: TransformerJsonToCsvSettingsEscapeChar;
  nullValue: string | null;
  rowIteratorPath: string;
  fields: Array<TransformerJsonToCsvSettingsFields>;
}

export type TransformerIgnoreSettings = object;

export type TransformerIsoSettings = object;

export interface TransformerSetpointToModbusSettings {
  mapping: Array<TransformerSetpointToModbusSettingsMapping>;
}

export interface TransformerSetpointToMqttSettings {
  mapping: Array<TransformerSetpointToMqttSettingsMapping>;
}

export interface TransformerSetpointToOpcuaSettings {
  mapping: Array<TransformerSetpointToOpcuaSettingsMapping>;
}

export interface TransformerTimeValuesToCsvSettings {
  filename: string;
  encoding: TransformerTimeValuesToCsvSettingsEncoding;
  header: boolean | null;
  delimiter: TransformerTimeValuesToCsvSettingsDelimiter;
  newline: TransformerTimeValuesToCsvSettingsNewline;
  quoteChar: TransformerTimeValuesToCsvSettingsQuoteChar;
  escapeChar: TransformerTimeValuesToCsvSettingsEscapeChar;
  pointIdColumnTitle: string;
  valueColumnTitle: string;
  timestampColumnTitle: string;
  timestampType: TransformerTimeValuesToCsvSettingsTimestampType;
  timestampFormat?: string;
  timezone?: Timezone;
  pointIdProcess: string | null;
}

export type TransformerTimeValuesToJsonSettings = object;

export interface TransformerTimeValuesToModbusSettings {
  mapping: Array<TransformerTimeValuesToModbusSettingsMapping>;
}

export interface TransformerTimeValuesToMqttSettings {
  mapping: Array<TransformerTimeValuesToMqttSettingsMapping>;
}

export interface TransformerTimeValuesToOianalyticsSettings {
  precision: TransformerTimeValuesToOianalyticsSettingsPrecision;
}

export interface TransformerTimeValuesToOpcuaSettings {
  mapping: Array<TransformerTimeValuesToOpcuaSettingsMapping>;
}

export type TransformerSettings =
  | TransformerCsvToMqttSettings
  | TransformerCsvToTimeValuesSettings
  | TransformerJsonToCsvSettings
  | TransformerIgnoreSettings
  | TransformerIsoSettings
  | TransformerSetpointToModbusSettings
  | TransformerSetpointToMqttSettings
  | TransformerSetpointToOpcuaSettings
  | TransformerTimeValuesToCsvSettings
  | TransformerTimeValuesToJsonSettings
  | TransformerTimeValuesToModbusSettings
  | TransformerTimeValuesToMqttSettings
  | TransformerTimeValuesToOianalyticsSettings
  | TransformerTimeValuesToOpcuaSettings;
