/**
 * Create a mock object for History Query Service
 */
export default jest.fn().mockImplementation(() => ({
  runHistoryQuery: jest.fn(),
  testNorth: jest.fn(),
  testSouth: jest.fn(),
  testSouthItem: jest.fn(),
  findById: jest.fn(),
  findAll: jest.fn(),
  createHistoryQuery: jest.fn(),
  getHistoryQueryDataStream: jest.fn(),
  updateHistoryQuery: jest.fn(),
  deleteHistoryQuery: jest.fn(),
  startHistoryQuery: jest.fn(),
  pauseHistoryQuery: jest.fn(),
  listSouthHistoryQueryItems: jest.fn(),
  listNorthHistoryQueryItems: jest.fn(),
  searchSouthHistoryQueryItems: jest.fn(),
  searchNorthHistoryQueryItems: jest.fn(),
  findAllSouthItemsForHistoryQuery: jest.fn(),
  findAllNorthItemsForHistoryQuery: jest.fn(),
  findSouthHistoryQueryItem: jest.fn(),
  findNorthHistoryQueryItem: jest.fn(),
  createSouthHistoryQueryItem: jest.fn(),
  createNorthHistoryQueryItem: jest.fn(),
  updateSouthHistoryQueryItem: jest.fn(),
  updateNorthHistoryQueryItem: jest.fn(),
  deleteSouthHistoryQueryItem: jest.fn(),
  deleteNorthHistoryQueryItem: jest.fn(),
  deleteAllSouthItemsForHistoryQuery: jest.fn(),
  deleteAllNorthItemsForHistoryQuery: jest.fn(),
  enableSouthHistoryQueryItem: jest.fn(),
  enableNorthHistoryQueryItem: jest.fn(),
  disableSouthHistoryQueryItem: jest.fn(),
  disableNorthHistoryQueryItem: jest.fn(),
  checkSouthCsvFileImport: jest.fn(),
  checkSouthCsvContentImport: jest.fn(),
  checkNorthCsvFileImport: jest.fn(),
  checkNorthCsvContentImport: jest.fn(),
  importSouthItems: jest.fn(),
  importNorthItems: jest.fn()
}));
