/**
 * Create a mock object for History Query Service
 */
export default jest.fn().mockImplementation(() => ({
  list: jest.fn(),
  findById: jest.fn(),
  create: jest.fn(),
  update: jest.fn(),
  delete: jest.fn(),
  start: jest.fn(),
  pause: jest.fn(),
  getHistoryDataStream: jest.fn(),
  testNorth: jest.fn(),
  testSouth: jest.fn(),
  testItem: jest.fn(),
  listItems: jest.fn(),
  searchItems: jest.fn(),
  findItemById: jest.fn(),
  createItem: jest.fn(),
  updateItem: jest.fn(),
  enableItem: jest.fn(),
  disableItem: jest.fn(),
  enableItems: jest.fn(),
  disableItems: jest.fn(),
  deleteItem: jest.fn(),
  deleteItems: jest.fn(),
  deleteAllItems: jest.fn(),
  checkImportItems: jest.fn(),
  importItems: jest.fn(),
  addOrEditTransformer: jest.fn(),
  removeTransformer: jest.fn(),
  searchCacheContent: jest.fn(),
  getCacheFileContent: jest.fn(),
  removeCacheContent: jest.fn(),
  removeAllCacheContent: jest.fn(),
  moveCacheContent: jest.fn(),
  moveAllCacheContent: jest.fn(),
  retrieveSecrets: jest.fn()
}));
