/**
 * Create a mock object for North Service
 */
export default jest.fn().mockImplementation(() => ({
  runNorth: jest.fn(),
  testNorth: jest.fn(),
  findById: jest.fn(),
  findAll: jest.fn(),
  getInstalledNorthManifests: jest.fn(),
  createNorth: jest.fn(),
  getNorthDataStream: jest.fn(),
  getErrorFiles: jest.fn(),
  getErrorFileContent: jest.fn(),
  removeErrorFiles: jest.fn(),
  retryErrorFiles: jest.fn(),
  removeAllErrorFiles: jest.fn(),
  retryAllErrorFiles: jest.fn(),
  getCacheFiles: jest.fn(),
  getCacheFileContent: jest.fn(),
  removeCacheFiles: jest.fn(),
  archiveCacheFiles: jest.fn(),
  removeAllCacheFiles: jest.fn(),
  getArchiveFiles: jest.fn(),
  getArchiveFileContent: jest.fn(),
  removeArchiveFiles: jest.fn(),
  retryArchiveFiles: jest.fn(),
  removeAllArchiveFiles: jest.fn(),
  retryAllArchiveFiles: jest.fn(),
  getCacheValues: jest.fn(),
  removeCacheValues: jest.fn(),
  removeAllCacheValues: jest.fn(),
  getErrorValues: jest.fn(),
  removeErrorValues: jest.fn(),
  removeAllErrorValues: jest.fn(),
  retryErrorValues: jest.fn(),
  retryAllErrorValues: jest.fn(),
  updateNorth: jest.fn(),
  deleteNorth: jest.fn(),
  startNorth: jest.fn(),
  stopNorth: jest.fn(),
  findSubscriptionsByNorth: jest.fn(),
  checkSubscription: jest.fn(),
  createSubscription: jest.fn(),
  deleteSubscription: jest.fn(),
  deleteAllSubscriptionsByNorth: jest.fn(),
  getNorthItems: jest.fn(),
  searchNorthItems: jest.fn(),
  findNorthConnectorItemById: jest.fn(),
  createItem: jest.fn(),
  updateItem: jest.fn(),
  deleteItem: jest.fn(),
  deleteAllItemsForNorthConnector: jest.fn(),
  enableItem: jest.fn(),
  disableItem: jest.fn(),
  checkCsvFileImport: jest.fn(),
  checkCsvContentImport: jest.fn(),
  importItems: jest.fn()
}));
