{
    "engine": {
        "port": 2223,
        "user": "admin",
        "password": "",
        "filter": [
            "127.0.0.1",
            "::1",
            "::ffff:127.0.0.1"
        ],
        "logParameters": {
            "consoleLevel": "debug",
            "fileLevel": "debug",
            "filename": "./logs/journal.log",
            "maxsize": 1000000,
            "maxFiles": 5,
            "tailable": true,
            "sqliteLevel": "debug",
            "sqliteFilename": "./logs/journal.db",
            "sqliteMaxFileSize": 50000000
        },
        "caching": {
            "cacheFolder": "./cache",
            "archiveMode": "delete",
            "archiveFolder": "./cache/archived/"
        },
        "scanModes": [
            {
                "scanMode": "everySecond",
                "cronTime": "* * * * * *"
            },
            {
                "scanMode": "every10Second",
                "cronTime": "* * * * * /10"
            },
            {
                "scanMode": "every1Min",
                "cronTime": "* * * * *"
            },
            {
                "scanMode": "listen",
                "cronTime": "listen"
            }
        ],
        "proxies": [
            {
                "name": "sss",
                "protocol": "http",
                "host": "hhh",
                "port": 123,
                "username": "uuu",
                "password": "E7Q+RY0Q3SO0ktrWp8C11RijQglJSZ6yO/uyIZJBPZ5sXsgQhuYtPp3SLKOpMYUCAKH/UVPcQe4ArMaCSQYkjgNiC40BsgrbspjY86V5X9fmT4WmRMjyZ8FKj6pdr4JGddQ0bzCkeCSe/9ZQdFNfOdbMma4aHy7TixMXCZubJ0I5rD14Kev37BHkRihcB1arvsA+8HSw7ybrjDmvnKYjBSyLTsdNic4hoHviuVD7d3uKBHciqgvDbB0udlRBTp3n2KFDhMo4hTjZkhtnosBknJYb2YopjzMcBp6q3uTHK/AdnBCXB1UpvkTziPtUpO/cZ7ZqMoWlX/p51X3R3tjfT7U3E5qkJi66rWa7QbcFhnWmdENQteNH5GkNnK1IjoR+1Ujt2rBt21abQCSyD+PpHfb9DMLKVoGBCSUsniMRALWNLYqcQdFYzGagy42J5cnHhr8zklKnSZ34ucjtwwcBPOeJa5fN475h055jCldExSxqVLnErsbfrG3dRDSuGqV5VZd8FhgJ8wAP55ltWdjGRxE45lIkOj+JSNtNOEjBw9lN4DWGrNtHi1nGNJwY3nhPDU2ooq08nYkT5AgdJWATZtNeeHA1W6Iqxz/OadkaXQI2wKKaCcKUDvJMAp2DFGkB+7ZQzcpRlLOIHuw3cM8st2fbR6vmdonwu0TQANq6+OU="
            },
            {
                "name": "ff",
                "protocol": "",
                "host": "tt",
                "port": 1,
                "username": "uii",
                "password": "VSLghj1ix8oUWfYF5RipmlBudZWoUcMgQiSEdo30MtzTy5/HOyhO4Yo19XsBmIynfBRMEeqPkBGCqO4BbHtY9JgxUnRqnimgTHjfbCKbgcqEZqVNuzubLhBCJT24D30DW5xGTqKOAD7vtqZp+bh1/PUwzIqP++RwK4daJVcSGZcWei/XqmZUBuCnQf/d1YachmnPXY1/qPNANExWoilVzrepkgpEI0Ve35BCOwVi/ZvJG6a0zL9ehXSHf1BuUF8ThyMLUI+yttYo6wvsq77gkZvEi0zdeJk82ukhMePAEZV804ikL2BrGp+J1F0A2MFP3ruY8Cn9f2DviBsQEO0PyBS4v0Z87od8SNx+wEv41UnMNhO0R7/Su1dBttZrBqq44iWJTPrGfjIVEynkSpfHcA/H6EOObg2azshdX/vhgPwLKlvcxVycetvOguGmsPsUx0nRB3HGnlO/21qidRM4vCfw1ZPI/5BFZkeTj/TwaK9ACEDs3vCEafid3FmGtLM+qk10t/mCE6TJ574zU8UZe/JNeJqVGBnoX5aug+ohCWB6ZHPfucLWsfne0L6zihQE2mEXY2cqpWWXoMDbm5rcBwQLntdvRWR2j64lnYwpLlRZrKjkpiwC2+44hGpfKtJsmTU9XfzMp/9lv3PJ2NQzqcmF+ue2e/yfXOvUA9fMxKI="
            }
        ],
        "engineName": "OIBus",
        "aliveSignal": {
            "enabled": false,
            "host": "https://demo.oianalytics.fr",
            "endpoint": "/api/optimistik/oibus/info",
            "authentication": {
                "type": "Basic",
                "username": "NFKET5UPQCFYL7OWLDB",
                "password": "fCytnTp9P9vNPZAL8+GxQfdE++sGUZdfzk3pou9bKRkPaaEWUSbo32Xv3Kv0pQItkrpB9JYkb0UKgA17lMyTuqoazf/KjbZwrec5divxSdMIfsD312WX++QlEk/0nC7PH6SiPawEkW8mIOO2Yl11Q2K8bWQr+r/RgLi9WA8NwUKjdtZW0Dmi8TKBWma2kmMGTJdW6UR3zy3oALplXfK9GhqV6klaCa9FL10p/48vzfOiQ4td3nrglD5wxCKReuprtlXWarILaMnt+7eJMr4ZUbTllzOY7jTX1BKfm+GrE557RMtsTrqi8MUh4pJ8Er7ebLqATxEbczW7bCd7gnUcdbzwLeTAatksm/xyrxCk5TbeO/tD1pDaicet6yB/myv/Bjdmi6ubDOhQOv8MBA6hxh4jvATnPL5YlL3xsD2R0BCeE7P46HnLaq/UDYk+bTXm2GXSD0mxZwVI4Y9YmGyizzq8eZ/JGy6bWVgO3Z/Yt3rRz+MYMA8Al5FGxwN0Xd5o6/8rU1M0nDWeWwiQYfuQH2q4q6pFg9DRKjC3+R0SOfhikNv5ZloNFPlQQbG6LJAYAYzoHAI6hA1L+OD1qAoebfWiM/r1D/EWG/kYHkmPC4vAJCBhms3CCFaFuu3tV+gSYjrGcYtMtrzXhM5imMhYeqFGku/O9xcPu2JevWJmsTU="
            },
            "id": "OIBus-test",
            "frequency": 300,
            "proxy": ""
        },
        "httpRequest": {
            "stack": "fetch",
            "timeout": 30
        }
    },
    "south": {
        "dataSources": [
            {
                "dataSourceId": "MQTTServer",
                "protocol": "MQTT",
                "enabled": false,
                "MQTT": {
                    "port": 8883,
                    "password": "BHeNoaflR+Ytjumprg/W3puiHKyQHsuOse0jII3QQCsEM9pw2h/5UQu/+4vrJabeCzKBpaX/k4veZbmrYEf8+XtzUHlm+uvMBj/r33HGhTAyqFJMrj6QIVvhW8jw+1aGR2jDgVOeCEEIV1jsfvhsNSdpE6lVJilkrWvOoLi1j0DuY8OuJm20x+pvFCj0EuQ2Dzyl+C6p7XhOGsJRZ5SCVnGLVqJvp7JTbNzhqbso1AF0Vtkznl14pxHCKxR2k+tfcSQAHE8wCgaAsgtt9auxn0im3pn0PdCzTGWZ+QiTC4cYtPb7YFgFj9MX25ZJpveneYfnABBKyVqq/Ubi/TjCbB5p7OymJUrtUDWm0mxSrU5Wb16Pw0fZbd+dQJFbd7HI8pSXzgHwXtaKwxDr528zSRdMofJKaXSJaEdetpeYvmZU5tywkirLTJYDfxXXzHvO5QZQb5gu6s4yo8RXv6R3kbfaDX7JkvKjzPyjXu2mZQ846CX9reNAXn7Itis/iT57hnrDNkIHVLsoblO4y8ZU9YJTDFWCzajsbysaq0dDcdGyvYuKqieaRGKF6M3uwG8o+vcdiZHuAhAn83EOxUQiglTehoGivUEkNExNQMfQlqK8ileOA+L2rZOggbiI6IgeP1szEmDFo7NfURIs7uP5IuJoKf0us3YnfiORNG/mTds=",
                    "server": "simulator.factorythings.com",
                    "mqttProtocol": "mqtts",
                    "username": "bai"
                },
                "points": [
                    {
                        "pointId": "/fttest.base/Tank 5.tank/Sensor22.temperature",
                        "scanMode": "listen",
                        "topic": "temperatureTank1"
                    },
                    {
                        "pointId": "/fttest.base/Tank 6.tank/Sensor23.temperature",
                        "scanMode": "listen",
                        "topic": "temperatureTank2"
                    }
                ]
            },
            {
                "dataSourceId": "SimulationServer",
                "protocol": "OPCUA",
                "enabled": false,
                "OPCUA": {
                    "opcuaPort": 53530,
                    "httpsPort": 53443,
                    "host": "35.180.179.217",
                    "endPoint": "Server/Simulation",
                    "timeOrigin": "server"
                },
                "points": [
                    {
                        "ns": 5,
                        "pointId": "/fttest.base/Tank 5.tank/333333.temperature",
                        "scanMode": "everySecond",
                        "s": "Counter1"
                    },
                    {
                        "ns": 5,
                        "pointId": "/fttest.base/Tank 5.tank/333333.temperature",
                        "scanMode": "everyNoon",
                        "s": "Random1"
                    }
                ]
            },
            {
                "dataSourceId": "SimulationServerBis",
                "protocol": "OPCUA",
                "enabled": false,
                "OPCUA": {
                    "opcuaPort": 53530,
                    "httpsPort": 53443,
                    "host": "35.180.179.217",
                    "endPoint": "Server/Simulation",
                    "timeOrigin": "server"
                },
                "points": [
                    {
                        "ns": 5,
                        "pointId": "/fttest.base/Tank 9.tank/333333.temperature",
                        "scanMode": "everySecond",
                        "s": "Sinusoid1"
                    }
                ]
            },
            {
                "dataSourceId": "PLC-35",
                "protocol": "Modbus",
                "enabled": false,
                "Modbus": {
                    "port": 502,
                    "host": "35.180.153.134"
                },
                "points": [
                    {
                        "pointId": "/fttest.base/Tank 3.tank/333333.fill_level",
                        "scanMode": "everySecond",
                        "address": "0x0031",
                        "type": "boolean"
                    },
                    {
                        "pointId": "/fttest.base/Tank 2.tank/222222.valve_state",
                        "scanMode": "everyNoon",
                        "address": "0x0f8",
                        "type": "boolean"
                    },
                    {
                        "pointId": "/fttest.base/Tank 2.tank/222222.fill_level",
                        "scanMode": "everySecond",
                        "address": "0x76a0",
                        "type": "boolean"
                    },
                    {
                        "pointId": "/fttest.base/Tank 2.tank/222333.fill_level",
                        "scanMode": "everySecond",
                        "address": "0x76b0",
                        "type": "boolean"
                    },
                    {
                        "pointId": "/fttest.base/Tank 3.tank/111111.valve_state",
                        "scanMode": "everySecond",
                        "address": "0x83a6",
                        "type": "boolean"
                    }
                ]
            },
            {
                "dataSourceId": "PLC-42",
                "protocol": "Modbus",
                "enabled": false,
                "Modbus": {
                    "port": 502,
                    "host": "35.180.153.134"
                },
                "points": [
                    {
                        "pointId": "/fttest.base/Tank4.tank/111111.fill_level",
                        "scanMode": "everySecond",
                        "address": "0x0f",
                        "type": "boolean"
                    },
                    {
                        "pointId": "/fttest.base/Tank4.tank/111111.flow_rate",
                        "scanMode": "everySecond",
                        "address": "0x20",
                        "type": "boolean"
                    }
                ]
            },
            {
                "dataSourceId": "FolderScanner",
                "protocol": "FolderScanner",
                "enabled": false,
                "FolderScanner": {
                    "minAge": 1000,
                    "inputFolder": "./tests/FolderScanner/input/",
                    "scanMode": "every5Second",
                    "regex": ".txt",
                    "preserve": false
                },
                "points": []
            },
            {
                "dataSourceId": "SQLDbToFile",
                "protocol": "SQLDbToFile",
                "enabled": false,
                "SQLDbToFile": {
                    "port": 1433,
                    "password": "ELMqtmgdbXXIBYOfhIm6GfSy/vYCZgUKRRBTfY+0h6mecX3ZhEE3oOjeI0oXJuIC6Sz/xZ5YxIrSqe92BeYtaKvEBu/7ARfjYVycmyznLLGhAGjLEhgG+1XaGehg1VZo0wpm4uxJIwySIV/Tof7tPhcLyrrj7p83pJZPDA0w+XIAFiSbPk4LkgE1vC8/HC5ZPTHakGYHbKJpcR0VdLQ6N1tOeYn3+TkLqarGhvuC5RRBUL+77wZIcXoNAV9r4AqbMtp3aRjPso8OU/mnb+DLFsNBBVvVnEawSUNu4BUUfZ/7B8EJAH7Mt5MBFNvhEO8fuSIkRr5cFW/OIOBi4g31JtyPbDKd/n/kPlGnClGxrqM+oiP1+3oKIdFVX8f4UI+NxqXNOchvoaeEHsgzlNWeWsHYfA0liErLM+SdXhkhfV37n/MFtc0TaISPD7G0oI6WWpCvFavlQtqsrZWSglQ+odYXDy/n+EEDSh1LxzzSJsIax8lU6wtD3dYyZLNw3YJ4Bya++WugIENt2atcehDT8J1ZpVhB6gq0zSOJG7RwbzVdCQJ89RgV3vKG4GS4Bp06c6P8GUP0ZVx6HPGL5GaKVCCjRBF7pTu/zYWDrH5DNEuho5orRQZ4zKjjhIYQuoQy2m4SaTMGf4WeAIoRJap0Z48jN/zFvaj0wlC2NAWfqvE=",
                    "connectionTimeout": 1000,
                    "requestTimeout": 1000,
                    "host": "192.168.0.11",
                    "driver": "mssql",
                    "username": "oibus_user",
                    "database": "oibus",
                    "query": "SELECT created_at AS timestamp, value1 AS temperature FROM oibus_test WHERE created_at > @date1",
                    "delimiter": ",",
                    "filename": "sql-@date.csv",
                    "scanMode": "everySecond",
                    "timeColumn": "timestamp",
                    "timezone": "Europe/Paris",
                    "dateFormat": "YYYY-MM-DD HH:mm:ss.SSS"
                },
                "scanMode": "every5Second",
                "points": []
            },
            {
                "dataSourceId": "OPC-HDA",
                "protocol": "OPCHDA",
                "enabled": false,
                "OPCHDA": {
                    "tcpPort": 3333,
                    "retryInterval": 10000,
                    "agentFilename": "./deps/win/HdaAgent/HdaAgent.exe",
                    "logLevel": "debug",
                    "host": "opcserver",
                    "serverName": "Matrikon.OPC.Simulation",
                    "maxReturnValues": 10000,
                    "maxReadInterval": 3600
                },
                "points": [
                    {
                        "pointId": "A13518/AI1/PV.CV",
                        "scanMode": "1000\r"
                    },
                    {
                        "pointId": "_FC42404/PID1/OUT.CV",
                        "scanMode": "10000\r"
                    },
                    {
                        "pointId": "_FC42404/PID1/PV.CV",
                        "scanMode": "10000\r"
                    },
                    {
                        "pointId": "ZY53182/DI1/OUT_D.CV",
                        "scanMode": "10000"
                    }
                ],
                "scanGroups": [
                    {
                        "scanMode": "every5Second",
                        "aggregate": "",
                        "resampling": "Minute"
                    },
                    {
                        "scanMode": "every20Second",
                        "aggregate": "",
                        "resampling": "Minute"
                    }
                ]
            },
            {
                "dataSourceId": "MQTTSimuServer",
                "protocol": "MQTT",
                "enabled": true,
                "MQTT": {
                    "password": "eYl2hXZxaFX+sETCVuQmoLJ7SK/1sTE81z+Xu55FYediF6ADBUlARcKIA5BgJMy6Cbsz9PmqVZOORkOPdl+Euuttw7aUfIrAjjezpzsePwP4mL1oyjlWoL2OoRwrhkwVWzwDeGTjb2DDh35EaXlrYYNHIhzbDtAzal9F+y3yeJnIwV29B6G8hk33WfkiiftOL0hMqcDQbGgUIvZdWzlV/WXky15gGAFbYMLOW2f0MNUOx/nVI6SnqfHV217whzlIrQVVsTgxsCDhphiR5xEpL1DzpIlKzk/I1knYrHF5RhGVqZHzPCtHL6gfmqDX465ALQX83j5EkocsirUATc9HyXAmHiI9nSVkVcEohHG+dlTUicvqx18kPFc2BZqaNvb2r3ufDp2BsItlwqIUfQJV/rlhGMy0oZKoi02uO7d3ycnNJ/9Pp7kjUNKl5vARsjXAG+0Ap62rGwdmwt0GdrhreR1giN1jcEgFNMlq5KqqLruhywOeYyki0x3df+SKF8ylskZROHtWGUMA53bgBkuY5yKUh+Yeay16BRC3P/DRIl6sgIhCRjsFe3MqfM7EVaZgD2YPBDTgGkI5DXPXwrwaKTf+XXKd2NV+RZkaBD2u5MK4HcLc3ihvyDm3rOVBn0syrAk4Ag/yh8vym/4FWjOmwy53PoSs1HkULjA4HBMYiqo=",
                    "url": "mqtt://localhost:1883",
                    "username": ".",
                    "timeStampOrigin": "payload",
                    "timeStampKey": "timestamp",
                    "timeStampFormat": "YYYY-MM-DDTHH:mm:ss.SSSZ",
                    "timeStampTimezone": "Europe/Paris"
                },
                "points": [
                    {
                        "pointId": "ANA/#",
                        "scanMode": "listen",
                        "topic": "_ANA/#"
                    }
                ]
            },
            {
                "dataSourceId": "MQTTSimuIOT",
                "protocol": "MQTT",
                "enabled": true,
                "MQTT": {
                    "password": "kB7gFUcqVA/x9R3zeyF3UAi2b+Brzw32wNXjqYaNL6nHJSpELigHvaJIv1705/prOBnno6j/oFgRT8YBX/p99LjB2p4wdFKJqEeOomONAyLMIc7fui/D5v/bvrUdaqelowvY9OsENvRBHpamHpKvxcPLV0I5gQmf5iSUZswW+AE5NOcnidQunzLgQ5ljrQMZgdPsM8cHMzFD/GMarFWh3qIkF0ofyIB6bfoQNJBLFtC69ouOsV+nlmu6TxgROp+i63I+ytXDOVY10wmbOFJBtb8iou8jSfCtwiIRF0wroapd/2ffQp4hSJ1ka0yKTFYMo0O5JwXETkQ9bEIhZlfKgvHu3cB/lq+BdhG/Yt8AWbFoDhk9GcbNeFZv6h9wBZz6EkQNCAX74HREWpTPGva7TQg2RQ44Q57v5E6EJbzd0w9BpiVWnoON2s2iyHdz/ZBwdXfS3EiGXizkiCIB0hdb1G79pBk0EW+E8k1vfLLKhChcwf3e7Xyustp1inrvqKcc0UOE+lznFRgOWAEeRmfPJYjO4boH6E02tahg/f7KpS1VC0xyI7G7YkCV8F1TlHzyQH461jufZsGzId3xTas6TA256tWmKmKBjc+4Hu20qvSBKMXd26keIrKCaThsOI/C/yQOAiWFq87tpHwmv5vYnwXAKxNP5YMAwsTlmhdUlR4=",
                    "url": "mqtt://localhost:1883",
                    "username": ".",
                    "timeStampOrigin": "oibus",
                    "timeStampKey": "timestamp",
                    "timeStampFormat": "YYYY-MM-DD HH:mm:ss.SSS",
                    "timeStampTimezone": "Europe/Paris"
                },
                "points": [
                    {
                        "pointId": "application/#",
                        "scanMode": "listen",
                        "topic": "_KURA/application/#"
                    }
                ]
            }
        ]
    },
    "north": {
        "applications": [
            {
                "applicationId": "c",
                "api": "Console",
                "enabled": true,
                "Console": {},
                "caching": {
                    "sendInterval": 10000,
                    "retryInterval": 5000,
                    "groupCount": 1,
                    "maxSendCount": 10000
                },
                "subscribedTo": []
            },
            {
                "applicationId": "monoiconnect",
                "api": "OIConnect",
                "enabled": false,
                "OIConnect": {
                    "authentication": {
                        "password": "",
                        "type": "Basic",
                        "username": ""
                    },
                    "host": "",
                    "endpoint": "",
                    "proxy": ""
                },
                "caching": {
                    "sendInterval": 10000,
                    "retryInterval": 5000,
                    "groupCount": 1000,
                    "maxSendCount": 10000
                },
                "subscribedTo": [],
                "OIAnalyticsFile": {
                    "stack": "fetch"
                }
            },
            {
                "applicationId": "simuidb",
                "api": "InfluxDB",
                "enabled": true,
                "InfluxDB": {
                    "password": "kFfMdmUFwJvP44aXaGxSPq1bu6quagnw1SEDHzI3q1FI30MATaW0PIpGEzF+R8uyByix7Egns5MPWkdQJSvWtILgfSSWFNMhSI5XvbLdxdH6KFEoK0NawH5rLwgFNx8hLUcjUYLZc42/Fmud7rd0ID8E4iuIisvFuA6EhSQ4IMKTR0rMXA8Vw3qb8JBaoUv19OOcMl0Fz+0apjNslHUNUJNLzM+905jVOnr3iiHVpkPvvhlfggGlyQhv6+Et4e/88+025y6v6PqAxqQJAWtmQwkP0/PDP1PM0arWyCS8Io6knfinPr3qZBavtAIWtGdlctocQQQjnCKEihVRE+mcsNiC/8Ts8fb0McGhcqXykKskNFRNhHMFojnoNVXDV7dnA43qXhKuwqXevgQCR/QffQgYXCTRfLqBcYmIGYKwdox+PQyhkAldkkM1oTXAqhfPthAhr0C6sfU9LD84oC+Eoelxxhk9OS6BuDmQ7HcuuBvUwDMpQr/1zyrx0I3+M+e79SnEbdY3xPxxsmgidOXkdJ3n04lXjl7+m3SbhT+3FzwsGbTosazt4PbHSm0waUIpfByRw1wasRsJjAdJR3fpunZYjVyIRq3zFe0+ZnW2xpzRfXvAOlkIbOJkUCUiH3drYl6lG6QY7xSUMbfQuvQhibqgn23KnB8yfqs0hZ2AYZ8=",
                    "user": ".",
                    "host": "http://localhost:8086",
                    "db": "simudata",
                    "precision": "ms",
                    "regExp": "(.*)\\/(.{2})(.)(.*)",
                    "measurement": "%1$s",
                    "tags": "Site=%2$s,Tranche=%3$s,Repere=%2$s%3$s%4$s"
                },
                "caching": {
                    "sendInterval": 10000,
                    "retryInterval": 5000,
                    "groupCount": 1000,
                    "maxSendCount": 5000
                },
                "subscribedTo": [
                    "MQTTSimuServer"
                ]
            },
            {
                "applicationId": "simumdb",
                "api": "MongoDB",
                "enabled": true,
                "MongoDB": {
                    "password": "nFvRnCV0JI2EEfpdIP42DvMq6Uk8fZEwpuobUwDK78MuvNeSWr96ejGQ03WYr+3vzYS6X27+uU9CSXZttAWzstuk/YNAF8PLCrikNMzYLtdZ5UQk4EVQJASx2l1iX/pHY5y+pDx5CYuPLXIeu0fw8tFme3RD7+vblnffuLhOvMVHAsb1wnUHdlsS6NM3ARMRcXrP+Ovdc7JgBxUtMaDfMQYGEv9olaqnZP0Zwisb3hDgnrzh6DVKPwKjqUYXZLnoSw4sytdCmMW0JqgaVa8LW9i9S5lAkkwZh3zkvMnv9RI/SsX90cPfgWbKvVGjmtaMvya5uHe2D/NBiomKNt7fsy2iGGzQmH690Jm09EPoNNLLx/byy5JiJ+QfaSxtggVKORyQ0mtPDLEG2eoF03pX3ABFpKYfcOrw/eHO3Iggrpaqf9Wdlw2KlybzuR4Flc8Pb2ikZSop7dIGXhAMjodAhUdcarePJdwraw2HnWhzSDSPJE1iab5G2+/DAmji6KamKbgRoD6DkbL+Tv1e+TwO/gf4mkD1b9yOv5K1Y1TbkNcKqDkQyzDWYVmk+LehDYp7nr4ync6D/32r1Baeavqe6uvvkCE94mrioYnKfmwAaZOy3P1tpwuj5PVL8fUQxpA5aVuF1UyxTL6n/51PHDfDpz6ezuEl3G2Ehjaehu9afR8=",
                    "user2": "admin",
                    "user": "",
                    "host": "localhost:27017",
                    "db": "simudata",
                    "regExp": "(.*)\\/(.{2})(.)(.*)",
                    "collection": "%1$s",
                    "indexFields": "Site:%2$s,Tranche:%3$s,Repere:%2$s%3$s%4$s",
                    "createCollection": true,
                    "createCollectionIndex": true,
                    "addTimestampToIndex": true,
                    "timeStampKey": "timestamp"
                },
                "caching": {
                    "sendInterval": 10000,
                    "retryInterval": 5000,
                    "groupCount": 1000,
                    "maxSendCount": 10000
                },
                "subscribedTo": [
                    "MQTTSimuServer"
                ]
            },
            {
                "applicationId": "simumqttkura",
                "api": "MQTTNorth",
                "enabled": true,
                "MQTTNorth": {
                    "password": "tld/tCWHDOAH8YPOBo3Lk+dcMW2AGWOCZYP6gP1u67WpMkd3NmMuVreV+rL1EuOd00wgOKlF2G1HIrJFF4r90elG1RTaNJERjAlSdDw5WFtT0t73q7ZgkbTfFpYRbQ2/KzVKqOy7s09C5boiBzsBxU1bIYMsX8WFtA6HlSn4Ol6NNBJrlveeC+/lGo/OlnuG/QTPiZW5NqTtkXBQW7HnNGeNcdfkDDNaA5RDfrUj4KjACYBcDlwdlh55OHUZ5oG5BbWOpQErEB9WQQ6GhfNWHuVbRWwRtuIb+SKFTNwbc8Sy5TrR2S0HWhDsSzgf6ykgLJWXhKwD6FQxNUU79zHJ4zWNoUbl/wYdriKMmf43XCULh7u29059Rp5D332Y4G2nbxHk2xQEKp/8qRe1iOzUU7AkCsQuzCpS6oFygjtIKey44JH4H7R0xvNqg6ZY++dIGBt6SrBZEe5eXqnc7BSLHI19gW8mYOvf8+RA3AOpY6ERs054rWWE+fuFjWs/YtLIaRBMnuQc/3EcH29dcczWSUgO1i7zWMIkensHod0SUCa0Sx89KUn6rKPle4nMJ97kiNJTpFNDIT4z84Xst0jV6UIj0OG1ap8qeLMh9g1cNjn5gEORJbyXukkdqURqazwVXnhkYch38m/Mj8e0n/J79llsZZCBvpCqqS01GjeKe3U=",
                    "url": "mqtt://localhost:1883",
                    "username": "."
                },
                "caching": {
                    "sendInterval": 1000,
                    "retryInterval": 2000,
                    "groupCount": 2,
                    "maxSendCount": 5
                },
                "subscribedTo": [
                    "MQTTSimuIOT"
                ]
            }
        ]
    },
    "schemaVersion": 8
}