name: Setup environment
description: "Checkout project, set up Node, build and deploy documentation"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.ref }}

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: documentation/package.json

    - name: Build documentation
      shell: bash
      run: |
        cd documentation
        npm ci
        npm run build

    - name: Deploy documentation
      if: ${{ steps.release.outputs.release_created }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Build output to publish to the `gh-pages` branch:
        publish_dir: ./documentation/build
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch:
        # https://github.com/actions/checkout/issues/13#issuecomment-724415212
        # The GH actions bot is used by default if you didn't specify the two fields.
        # You can swap them out with your own user credentials.
        user_name: Optimistik SAS
        user_email: optimistiksas@users.noreply.github.com