name: Setup environment
description: "Checkout project, set up Node and install dependencies for Backend, Frontend, and Launcher"
inputs:
  cache_version:
    description: 'Value gets appended to the cache key to invalidate it manually'
    required: true
  prerelease:
    description: 'Is it a prerelease or not'
    required: false
    default: 'false'
  tag_name:
    description: 'Tag name used for version bumping'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: backend/package.json

      # 1. Backend Cache
    - name: Cache Backend
      id: cache-backend
      uses: actions/cache@v4
      with:
       path: backend/node_modules
       key: backend-deps-${{ runner.os }}-${{ inputs.cache_version }}-${{ hashFiles('backend/package-lock.json') }}

      # 2. Frontend Cache
    - name: Cache Frontend
      id: cache-frontend
      uses: actions/cache@v4
      with:
       path: frontend/node_modules
       key: frontend-deps-${{ runner.os }}-${{ inputs.cache_version }}-${{ hashFiles('frontend/package-lock.json') }}

      # 3. Launcher Cache
    - name: Cache Launcher
      id: cache-launcher
      uses: actions/cache@v4
      with:
        path: launcher/node_modules
        key: launcher-deps-${{ runner.os }}-${{ inputs.cache_version }}-${{ hashFiles('launcher/package-lock.json') }}

    # --- INSTALL DEPENDENCIES ---
    - name: Install Backend Dependencies
      if: ${{ steps.cache-backend.outputs.cache-hit != 'true' }}
      working-directory: backend
      shell: bash
      run: npm ci

    - name: Install Frontend Dependencies
      if: ${{ steps.cache-frontend.outputs.cache-hit != 'true' }}
      working-directory: frontend
      shell: bash
      run: npm ci

    - name: Install Launcher Dependencies
      if: ${{ steps.cache-launcher.outputs.cache-hit != 'true' }}
      working-directory: launcher
      shell: bash
      run: npm ci

    # --- BUMP VERSIONS (After Install) ---

    - name: Bump versions if pre-release
      if: ${{ inputs.prerelease == 'true' }}
      shell: bash
      run: |
        TAG_NAME=${{ inputs.tag_name }}
        echo "Bumping versions to $TAG_NAME"
        
        bump_version() {
          if [ -d "$1" ]; then
            echo "Bumping $1..."
            cd $1
            jq --arg version "$TAG_NAME" '.version = $version' package.json > tmp.json && mv tmp.json package.json
            cd ..
          fi
        }

        bump_version "backend"
        bump_version "frontend"
        bump_version "launcher"
        bump_version "documentation"