name: Setup environment
description: "Checkout project, set up Node and install dependencies for Backend, Frontend, and Launcher"
inputs:
  cache_version:
    description: 'Value gets appended to the cache key to invalidate it manually'
    required: true
  prerelease:
    description: 'Is it a prerelease or not'
    required: false
    default: 'false'
  tag_name:
    description: 'Tag name used for version bumping'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: backend/package.json

    - name: Load cached node_modules
      id: cache-deps
      uses: actions/cache@v5
      with:
        path: |
          backend/node_modules
          frontend/node_modules
          launcher/node_modules
          backend/package-lock.json
          frontend/package-lock.json
          launcher/package-lock.json
        # Key includes hashes of ALL lockfiles + cache_version input
        key: oibus-deps-${{ runner.os }}-${{ runner.arch }}-${{ inputs.cache_version }}-${{ hashFiles('backend/package-lock.json', 'frontend/package-lock.json', 'launcher/package-lock.json') }}

    - name: Bump versions if pre-release
      if: ${{ inputs.prerelease == 'true' }}
      shell: bash
      run: |
        TAG_NAME=${{ inputs.tag_name }}
        echo "Bumping versions to $TAG_NAME"
        
        # Function to bump version in a directory
        bump_version() {
          if [ -d "$1" ]; then
            echo "Bumping $1..."
            cd $1
            jq --arg version "$TAG_NAME" '.version = $version' package.json > tmp.json && mv tmp.json package.json
            cd ..
          fi
        }

        bump_version "backend"
        bump_version "frontend"
        bump_version "launcher"
        bump_version "documentation"

    # 5. Install Dependencies (All Projects)
    # We install dependencies only if the combined cache was NOT hit
    - name: Install Backend Dependencies
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      working-directory: backend
      shell: bash
      run: npm ci

    - name: Install Frontend Dependencies
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      working-directory: frontend
      shell: bash
      run: npm ci

    - name: Install Launcher Dependencies
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      working-directory: launcher
      shell: bash
      run: npm ci