export default {
  name: 'CsvToHttp',
  category: 'api',
  modes: {
    files: true,
    points: false,
  },
  settings: [
    {
      key: 'applicativeHostUrl',
      label: 'Host url',
      type: 'OibText',
      newRow: true,
      validators: [{ key: 'required' }, { key: 'pattern', params: { pattern: '^(http:\\/\\/|https:\\/\\/|HTTP:\\/\\/|HTTPS:\\/\\/).*' } }],
      readDisplay: true,
    },
    {
      key: 'requestMethod',
      type: 'OibSelect',
      options: ['GET', 'POST', 'PUT', 'PATCH'],
      label: 'HTTP Method',
      defaultValue: 'POST',
      newRow: false,
      validators: [{ key: 'required' }],
    },
    {
      key: 'bodyMaxLength',
      type: 'OibNumber',
      label: 'Max length of the body',
      defaultValue: 100,
      newRow: false,
      validators: [{ key: 'required' }, { key: 'min', params: { min: 1 } }, { key: 'max', params: { max: 10_000 } }],
    },
    {
      key: 'acceptUnconvertedRows',
      type: 'OibCheckbox',
      label: 'Accept unconverted rows',
      defaultValue: false,
      newRow: false,
    },
    {
      key: 'authentication',
      type: 'OibAuthentication',
      label: 'Authentication',
      newRow: true,
    },
    {
      key: 'csvDelimiter',
      type: 'OibSelect',
      options: [',', ';'],
      label: 'CSV delimiter',
      defaultValue: ';',
      validators: [{ key: 'required' }],
      newRow: true,
    },
    {
      key: 'mapping',
      type: 'OibTable',
      rows: {
        csvField: {
          type: 'OibText',
          newRow: false,
          label: 'Header in csv file',
          defaultValue: '',
        },
        httpField: {
          type: 'OibText',
          newRow: false,
          label: 'Field in http body',
          defaultValue: '',
        },
        type: {
          type: 'OibSelect',
          newRow: false,
          label: 'Type',
          options: ['string', 'integer', 'float', 'timestamp', 'date (ISO)', 'short date (yyyy-mm-dd)'],
          md: 3,
          defaultValue: 'string',
        },
      },
    },
    { key: 'proxy', type: 'OibProxy', label: 'Proxy', newRow: true },
  ],
}
