// DO NOT EDIT THIS BY HAND!
// This file is auto-generated by the script located backend/src/settings-interface.generator.ts
// To update the typescript model run npm run generate-settings-interface on the backend project

const NORTH_AZURE_BLOB_SETTINGS_AUTHENTICATIONS = ['accessKey', 'sasToken', 'aad', 'external'] as const
export type NorthAzureBlobSettingsAuthentication = (typeof NORTH_AZURE_BLOB_SETTINGS_AUTHENTICATIONS)[number];

const NORTH_CSV_TO_HTTP_SETTINGS_REQUEST_METHODS = ['GET', 'POST', 'PUT', 'PATCH'] as const
export type NorthCsvToHttpSettingsRequestMethod = (typeof NORTH_CSV_TO_HTTP_SETTINGS_REQUEST_METHODS)[number];

const NORTH_CSV_TO_HTTP_SETTINGS_CSV_DELIMITERS = [',', ';'] as const
export type NorthCsvToHttpSettingsCsvDelimiter = (typeof NORTH_CSV_TO_HTTP_SETTINGS_CSV_DELIMITERS)[number];

const NORTH_INFLUX_D_B_SETTINGS_PRECISIONS = ['ns', 'u', 'ms', 's', 'm', 'h'] as const
export type NorthInfluxDBSettingsPrecision = (typeof NORTH_INFLUX_D_B_SETTINGS_PRECISIONS)[number];

const NORTH_MQTT_SETTINGS_QOSS = ['0', '1', '2'] as const
export type NorthMqttSettingsQos = (typeof NORTH_MQTT_SETTINGS_QOSS)[number];

const NORTH_O_I_ANALYTICS_SETTINGS_SPECIFIC_SETTINGS_AUTHENTICATIONS = ['basic', 'aad-client-secret', 'aad-certificate'] as const
export type NorthOIAnalyticsSettingsSpecificSettingsAuthentication = (typeof NORTH_O_I_ANALYTICS_SETTINGS_SPECIFIC_SETTINGS_AUTHENTICATIONS)[number];

const NORTH_REST_A_P_I_SETTINGS_AUTHENTICATION_TYPES = ['none', 'basic', 'bearer', 'api-key'] as const
export type NorthRestAPISettingsAuthenticationType = (typeof NORTH_REST_A_P_I_SETTINGS_AUTHENTICATION_TYPES)[number];

export interface NorthOIAnalyticsSettingsSpecificSettings {
  host: string;
  acceptUnauthorized: boolean;
  authentication: NorthOIAnalyticsSettingsSpecificSettingsAuthentication;
  accessKey?: string;
  secretKey?: string | null;
  tenantId?: string | null;
  clientId?: string;
  clientSecret?: string | null;
  certificateId?: string | null;
  scope?: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthRestAPISettingsAuthentication {
  type: NorthRestAPISettingsAuthenticationType;
  username?: string;
  password?: string | null;
  token?: string | null;
  apiKeyHeader?: string | null;
  apiKey?: string | null;
}

interface BaseNorthSettings {}

export interface NorthAmazonS3Settings extends BaseNorthSettings {
  bucket: string;
  region: string;
  folder: string;
  accessKey: string;
  secretKey: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthAzureBlobSettings extends BaseNorthSettings {
  account: string;
  container: string;
  path: string | null;
  authentication: NorthAzureBlobSettingsAuthentication;
  sasToken?: string | null;
  accessKey?: string | null;
  tenantId?: string | null;
  clientId?: string | null;
  clientSecret?: string | null;
}

export interface NorthConsoleSettings extends BaseNorthSettings {
  verbose: boolean;
}

export interface NorthCsvToHttpSettings extends BaseNorthSettings {
  applicativeHostUrl: string;
  requestMethod: NorthCsvToHttpSettingsRequestMethod;
  bodyMaxLength: number;
  acceptUnconvertedRows: boolean | null;
  csvDelimiter: NorthCsvToHttpSettingsCsvDelimiter;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthFileWriterSettings extends BaseNorthSettings {
  outputFolder: string;
  prefix: string | null;
  suffix: string | null;
}

export interface NorthInfluxDBSettings extends BaseNorthSettings {
  host: string;
  database: string;
  username: string;
  password: string | null;
  timestampPathInDataValue: string | null;
  precision: NorthInfluxDBSettingsPrecision;
  regExp: string;
  measurement: string;
  tags: string | null;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
}

export interface NorthMongoDBSettings extends BaseNorthSettings {
  host: string;
  database: string;
  username: string;
  password: string | null;
  regExp: string;
  collection: string;
  indexFields: string | null;
  createCollection: boolean;
  timestampKey: string;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
  timestampPathInDataValue: string | null;
}

export interface NorthMqttSettings extends BaseNorthSettings {
  url: string;
  qos: NorthMqttSettingsQos;
  username: string | null;
  password: string | null;
  certFile: string | null;
  keyFile: string | null;
  caFile: string | null;
  rejectUnauthorized: boolean | null;
  regExp: string;
  topic: string;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
}

export interface NorthOIAnalyticsSettings extends BaseNorthSettings {
  useOiaModule: boolean;
  timeout: number;
  compress: boolean;
  specificSettings?: NorthOIAnalyticsSettingsSpecificSettings | null;
}

export interface NorthOIBusSettings extends BaseNorthSettings {
  host: string;
  acceptUnauthorized: boolean;
  timeout: number;
  username: string;
  password: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthRestAPISettings extends BaseNorthSettings {
  host: string;
  acceptUnauthorized: boolean;
  timeout: number;
  valuesEndpoint: string;
  fileEndpoint: string;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
  authentication: NorthRestAPISettingsAuthentication;
}

export interface NorthTimescaleDBSettings extends BaseNorthSettings {
  username: string;
  password: string | null;
  host: string;
  database: string;
  regExp: string;
  table: string;
  optFields: string | null;
  timestampPathInDataValue: string | null;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
}

export interface NorthWatsySettings extends BaseNorthSettings {
  MQTTUrl: string;
  port: number;
  username: string | null;
  password: string | null;
  applicativeHostUrl: string;
  secretKey: string | null;
}

export type NorthSettings =
  | NorthAmazonS3Settings
  | NorthAzureBlobSettings
  | NorthConsoleSettings
  | NorthCsvToHttpSettings
  | NorthFileWriterSettings
  | NorthInfluxDBSettings
  | NorthMongoDBSettings
  | NorthMqttSettings
  | NorthOIAnalyticsSettings
  | NorthOIBusSettings
  | NorthRestAPISettings
  | NorthTimescaleDBSettings
  | NorthWatsySettings

