// DO NOT EDIT THIS BY HAND!
// This file is auto-generated by the script located backend/src/settings-interface.generator.ts
// To update the typescript model run npm run generate-settings-interface on the backend project

export type NorthAzureBlobSettingsAuthentication = 'accessKey' | 'sasToken' | 'aad' | 'external';

export type NorthCsvToHttpSettingsRequestMethod = 'GET' | 'POST' | 'PUT' | 'PATCH';

export type NorthCsvToHttpSettingsCsvDelimiter = ',' | ';';

export type NorthInfluxDBSettingsPrecision = 'ns' | 'u' | 'ms' | 's' | 'm' | 'h';

export type NorthMqttSettingsQos = '0' | '1' | '2';

export type NorthOIAnalyticsSettingsSpecificSettingsAuthentication = 'basic' | 'aad-client-secret' | 'aad-certificate';

export type NorthRestAPISettingsAuthenticationType = 'none' | 'basic' | 'bearer' | 'api-key';

export type NorthSFTPSettingsAuthentication = 'password' | 'private-key';

export interface NorthOIAnalyticsSettingsSpecificSettings {
  host: string;
  acceptUnauthorized: boolean;
  authentication: NorthOIAnalyticsSettingsSpecificSettingsAuthentication;
  accessKey?: string;
  secretKey?: string | null;
  tenantId?: string | null;
  clientId?: string;
  clientSecret?: string | null;
  certificateId?: string | null;
  scope?: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthRestAPISettingsAuthentication {
  type: NorthRestAPISettingsAuthenticationType;
  username?: string;
  password?: string | null;
  token?: string | null;
  apiKeyHeader?: string | null;
  apiKey?: string | null;
}

export interface NorthAmazonS3Settings {
  bucket: string;
  region: string;
  folder: string;
  accessKey: string;
  secretKey: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthAzureBlobSettings {
  useCustomUrl: boolean;
  account?: string;
  customUrl?: string;
  container: string;
  path: string | null;
  authentication: NorthAzureBlobSettingsAuthentication;
  sasToken?: string | null;
  accessKey?: string | null;
  tenantId?: string | null;
  clientId?: string | null;
  clientSecret?: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthConsoleSettings {
  verbose: boolean;
}

export interface NorthCsvToHttpSettings {
  applicativeHostUrl: string;
  requestMethod: NorthCsvToHttpSettingsRequestMethod;
  bodyMaxLength: number;
  acceptUnconvertedRows: boolean | null;
  csvDelimiter: NorthCsvToHttpSettingsCsvDelimiter;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthFileWriterSettings {
  outputFolder: string;
  prefix: string | null;
  suffix: string | null;
}

export interface NorthInfluxDBSettings {
  host: string;
  database: string;
  username: string;
  password: string | null;
  timestampPathInDataValue: string | null;
  precision: NorthInfluxDBSettingsPrecision;
  regExp: string;
  measurement: string;
  tags: string | null;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
}

export interface NorthMongoDBSettings {
  host: string;
  database: string;
  username: string;
  password: string | null;
  regExp: string;
  collection: string;
  indexFields: string | null;
  createCollection: boolean;
  timestampKey: string;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
  timestampPathInDataValue: string | null;
}

export interface NorthMqttSettings {
  url: string;
  qos: NorthMqttSettingsQos;
  username: string | null;
  password: string | null;
  certFile: string | null;
  keyFile: string | null;
  caFile: string | null;
  rejectUnauthorized: boolean | null;
  regExp: string;
  topic: string;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
}

export interface NorthOIAnalyticsSettings {
  useOiaModule: boolean;
  timeout: number;
  compress: boolean;
  specificSettings?: NorthOIAnalyticsSettingsSpecificSettings | null;
}

export interface NorthOIBusSettings {
  host: string;
  acceptUnauthorized: boolean;
  timeout: number;
  username: string;
  password: string | null;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
}

export interface NorthRestAPISettings {
  host: string;
  acceptUnauthorized: boolean;
  timeout: number;
  valuesEndpoint: string;
  fileEndpoint: string;
  useProxy: boolean;
  proxyUrl?: string;
  proxyUsername?: string | null;
  proxyPassword?: string | null;
  authentication: NorthRestAPISettingsAuthentication;
}

export interface NorthSFTPSettings {
  host: string;
  port: number;
  authentication: NorthSFTPSettingsAuthentication;
  username: string | null;
  password?: string | null;
  privateKey?: string;
  passphrase?: string | null;
  remoteFolder: string;
  prefix: string | null;
  suffix: string | null;
}

export interface NorthTimescaleDBSettings {
  username: string;
  password: string | null;
  host: string;
  database: string;
  regExp: string;
  table: string;
  optFields: string | null;
  timestampPathInDataValue: string | null;
  useDataKeyValue: boolean;
  keyParentValue: string | null;
}

export interface NorthWatsySettings {
  MQTTUrl: string;
  port: number;
  username: string | null;
  password: string | null;
  applicativeHostUrl: string;
  secretKey: string | null;
}

export type NorthSettings =
  | NorthAmazonS3Settings
  | NorthAzureBlobSettings
  | NorthConsoleSettings
  | NorthCsvToHttpSettings
  | NorthFileWriterSettings
  | NorthInfluxDBSettings
  | NorthMongoDBSettings
  | NorthMqttSettings
  | NorthOIAnalyticsSettings
  | NorthOIBusSettings
  | NorthRestAPISettings
  | NorthSFTPSettings
  | NorthTimescaleDBSettings
  | NorthWatsySettings;
