export default {
  name: 'TimescaleDB',
  category: 'database',
  modes: {
    files: false,
    points: true,
  },
  settings: [
    {
      key: 'username',
      type: 'OibText',
      label: 'User',
      defaultValue: '',
      validators: [{ key: 'required' }],
      readDisplay: true,
    },
    {
      key: 'password',
      type: 'OibSecret',
      label: 'Password',
      defaultValue: '',
      newRow: false,
      validators: [{ key: 'minLength', params: { min: 1 } }, { key: 'maxLength', params: { max: 255 } }],
      readDisplay: false,
    },
    {
      key: 'host',
      type: 'OibText',
      label: 'Host',
      validators: [{ key: 'required' }, { key: 'pattern', params: { pattern: '^(http:\\/\\/|https:\\/\\/|HTTP:\\/\\/|HTTPS:\\/\\/).*' } }],
      newRow: true,
      readDisplay: true,
    },
    {
      key: 'database',
      type: 'OibText',
      newRow: false,
      label: 'Database',
      defaultValue: '',
      validators: [{ key: 'required' }],
      readDisplay: true,
    },
    {
      key: 'regExp',
      type: 'OibText',
      label: 'RegExp',
      defaultValue: '(.*)',
      validators: [{ key: 'required' }],
    },
    {
      key: 'table',
      type: 'OibText',
      label: 'Table',
      defaultValue: '%1$s',
      validators: [{ key: 'required' }],
    },
    {
      key: 'optFields',
      type: 'OibText',
      label: 'Optional fields',
      defaultValue: '',
      newRow: false,
      validators: [{ key: 'minLength', params: { minLength: 1 } }, { key: 'maxLength', params: { maxLength: 255 } }],
    },
    {
      key: 'timestampPathInDataValue',
      type: 'OibText',
      label: 'Timestamp path in data value',
      defaultValue: '',
      newRow: true,
    },
    {
      key: 'useDataKeyValue',
      type: 'OibCheckbox',
      label: 'Use key "value" of Json "data"',
      defaultValue: false,
      validators: ['required'],
    },
    {
      key: 'keyParentValue',
      type: 'OibText',
      label: 'Key parent value',
      defaultValue: '',
    },
  ],
}
