export default {
  name: 'OPCHDA',
  category: 'iot',
  description: 'OPCHDA description',
  modes: {
    subscription: false,
    lastPoint: false,
    lastFile: false,
    historyPoint: true,
    historyFile: false,
  },
  settings: [
    {
      key: 'agentFilename',
      type: 'OibText',
      label: 'Agent file path',
      defaultValue: '\\HdaAgent\\HdaAgent.exe',
      newRow: true,
      validators: ['required'],
      readDisplay: true,
    },
    {
      key: 'tcpPort',
      type: 'OibNumber',
      label: 'HDA Agent Port',
      defaultValue: '2224',
      newRow: false,
      validators: ['required'],
      readDisplay: true,
    },
    {
      key: 'logLevel',
      type: 'OibSelect',
      label: 'Agent log level',
      options: ['trace', 'debug', 'info', 'warning', 'error'],
      defaultValue: 'debug',
      newRow: false,
      validators: ['required'],
      readDisplay: false,
    },
    {
      key: 'host',
      type: 'OibText',
      label: 'Host',
      newRow: true,
      validators: ['required'],
      readDisplay: false,
    },
    {
      key: 'serverName',
      type: 'OibText',
      label: 'Server name',
      newRow: false,
      validators: ['required'],
      readDisplay: false,
    },
    {
      key: 'readTimeout',
      type: 'OibNumber',
      label: 'Read timeout (ms)',
      defaultValue: 180_000,
      newRow: true,
      validators: ['required', ['min', 100], ['max', 3_600_000]],
      readDisplay: false,
    },
    {
      key: 'retryInterval',
      type: 'OibNumber',
      label: 'Retry interval (ms)',
      defaultValue: 10_000,
      newRow: false,
      validators: ['required', ['min', 100], ['max', 3_600_000]],
      readDisplay: false,
    },
    {
      key: 'maxReadInterval',
      type: 'OibNumber',
      label: 'Max read interval (s)',
      newRow: true,
      validators: ['required'],
      readDisplay: false,
    },
    {
      key: 'readIntervalDelay',
      type: 'OibNumber',
      label: 'Read interval delay (ms)',
      defaultValue: 200,
      newRow: false,
      validators: ['required', ['min', 100], ['max', 3_600_000]],
      readDisplay: false,
    },
    {
      key: 'maxReturnValues',
      type: 'OibNumber',
      label: 'Max return values',
      defaultValue: 1000,
      newRow: false,
      validators: ['required'],
      readDisplay: false,
    },
  ],
  items: [
    {
      key: 'scanMode',
      type: 'OibScanMode',
      label: 'Scan mode',
      validators: ['required'],
      readDisplay: true,
    },
    {
      key: 'aggregate',
      type: 'OibSelect',
      label: 'Aggregate',
      options: ['Raw', 'Average', 'Minimum', 'Maximum', 'Count'],
      defaultValue: 'Raw',
      readDisplay: true,
    },
    {
      key: 'resampling',
      type: 'OibSelect',
      label: 'Resampling',
      options: ['None', 'Second', '10 Seconds', '30 Seconds', 'Minute', 'Hour', 'Day'],
      defaultValue: 'None',
      readDisplay: true,
    },
    {
      key: 'nodeId',
      type: 'OibText',
      label: 'Node ID',
      defaultValue: '',
      readDisplay: true,
    },
  ],
}
