name: Run unit tests
description: "Run lint, build and tests"

runs:
  using: "composite"
  steps:
    - name: Run backend linting
      shell: bash
      working-directory: backend
      run: pnpm run lint

    - name: Run frontend linting
      shell: bash
      working-directory: frontend
      run: pnpm run lint

    - name: Run launcher linting
      shell: bash
      working-directory: launcher
      run: pnpm run lint

    - name: Build backend
      shell: bash
      working-directory: backend
      run: pnpm run build

    - name: Run backend unit tests
      shell: bash
      working-directory: backend
      run: pnpm test

    - name: Build frontend
      shell: bash
      working-directory: frontend
      run: pnpm run build

    - name: Run frontend unit tests
      shell: bash
      working-directory: frontend
      run: pnpm test
