name: Run unit tests
description: "Run tests"

runs:
  using: "composite"
  steps:
    - name: Run lint
      shell: bash
      run: npm run lint

    - name: Run backend unit tests
      shell: bash
      run: npm test

