import { Knex } from 'knex';

const CERTIFICATES_TABLE = 'certificates';

/**
 * Adds certificate_chain to certificates, holding a PEM bundle of intermediate/root CAs supplied
 * when importing an externally-issued certificate. Null for self-signed certificates generated by
 * OIBus.
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.alterTable(CERTIFICATES_TABLE, t => {
    t.string('certificate_chain').nullable();
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.alterTable(CERTIFICATES_TABLE, t => {
    t.dropColumn('certificate_chain');
  });
}
