export default {
  name: 'WATSY',
  category: 'api',
  modes: {
    files: false,
    points: true,
  },
  settings: [
    {
      key: 'MQTTUrl',
      type: 'OibText',
      label: 'MQTT URL',
      newRow: true,
      validators: [{ key: 'required' },
        { key: 'pattern', params: { pattern: '^(mqtt:\\/\\/|mqtts:\\/\\/|tcp:\\/\\/|tls:\\/\\/|ws:\\/\\/|wss:\\/\\/).*' } }],
      readDisplay: true,
    },
    {
      key: 'port',
      type: 'OibNumber',
      label: 'Port',
      defaultValue: 1883,
      newRow: false,
      validators: [{ key: 'required' }, { key: 'min', params: { min: 1 } }, { key: 'max', params: { max: 65535 } }],
      readDisplay: true,
    },
    {
      key: 'username',
      type: 'OibText',
      label: 'Username',
      defaultValue: '',
      newRow: true,
      readDisplay: false,
    }, {
      key: 'password',
      type: 'OibSecret',
      label: 'Password',
      defaultValue: '',
      newRow: false,
      readDisplay: false,
    },
    {
      key: 'applicativeHostUrl',
      type: 'OibText',
      label: 'Applicative Host URL',
      defaultValue: '',
      validators: [{ key: 'required' }, { key: 'pattern', params: { pattern: '^(http:\\/\\/|https:\\/\\/|HTTP:\\/\\/|HTTPS:\\/\\/).*' } }],
      readDisplay: true,

    },
    {
      key: 'secretKey',
      type: 'OibSecret',
      label: 'Token',
      newRow: false,
      validators: [{ key: 'minLength', params: { minLength: 1 } }, { key: 'maxLength', params: { maxLength: 255 } }],
      defaultValue: '',
    },
  ],
}
