version: '3.5'
services:
    mysql:
        container_name: oibus-mysql
        image: 'mysql:8.0-oracle'
        ports:
            - ${FORWARD_MYSQL_PORT:-5306}:3306
        environment:
            TZ: 'Europe/Paris'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-oibus123}'
            MYSQL_DATABASE: '${DB_DATABASE:-oibus}'
            MYSQL_USER: '${DB_USERNAME:-oibus}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-oibus123}'
        volumes:
            - /var/lib/mysql

    postgresql:
         container_name: oibus-postgresql
         image: postgres
         volumes:
             - /var/lib/postgresql/data
         ports:
             - ${FORWARD_POSTGRESQL_PORT:-5432}:5432
         environment:
             - TZ=Europe/Paris
             - POSTGRES_USER=${DB_USERNAME:-oibus}
             - POSTGRES_PASSWORD=${DB_PASSWORD:-oibus123}
             - POSTGRES_DB=${DB_DATABASE:-oibus}

    mssql:
         container_name: oibus-mssql
         image: mcr.microsoft.com/azure-sql-edge:latest
         ports:
             - ${FORWARD_MSSQL_PORT:-1433}:1433
         environment:
             SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Oibus123@}
             ACCEPT_EULA: "Y"

#    rabbitmq:
#         container_name: oibus-rabbitmq
#         image: rabbitmq:3-management
#         ports:
#             - ${FORWARD_RABBITMQ_PORT:-5672}:5672

#    mosquitto:
#         container_name: oibus-mosquitto
#         image: eclipse-mosquitto
#         ports:
#             - ${FORWARD_MOSQUITTO_PORT:-1883}:1883

#    opcuaserver:
#         container_name: oibus-opcua
#         image: mcr.microsoft.com/iotedge/opc-plc:latest
#         restart: always
#         ports:
#             - 8080:8080
#             - 50000:50000
