name: Build OIBus binaries

on: workflow_call

jobs:
  build-binaries:
    name: Build on ${{ matrix.config['os'] }}
    runs-on: ${{ matrix.config['os'] }}
    strategy:
      matrix:
        config:
          - { os: 'macos-latest',   platform: 'macos', archiveName: 'OIBus-macos.zip', zip: 'zip -r' }
          - { os: 'windows-latest', platform: 'win',   archiveName: 'OIBus-win32x64.zip', zip: '7z a -tzip' }
          - { os: 'ubuntu-latest',  platform: 'linux', archiveName: 'OIBus-linux.zip', zip: 'zip -r' }
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}

      - name: Package OIBus for ${{ matrix.config['platform'] }}
        run: |
          npm run build-${{ matrix.config['platform'] }}
          cd dist/${{ matrix.config['platform'] }}
          ./oibus --config ../../tests/oibus.json --check true
          ${{ matrix.config['zip'] }} ../${{ matrix.config['archiveName'] }} .

      - name: Upload artifact ${{ matrix.config['archiveName'] }}
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/${{ matrix.config['archiveName'] }}

      - name: Package Windows installer
        if: ${{ matrix.config['platform'] == 'win' }}
        run: npm run build-win-setup
        working-directory: ./dist/win
        shell: cmd

      - name: Rename windows installer
        if: ${{ matrix.config['platform'] == 'win' }}
        run: mv ./dist/win-setup-release/oibus_setup.exe ./dist/win-setup-release/OIBus-setup-win32x64.exe

      - name: Upload Windows installer
        if: ${{ matrix.config['platform'] == 'win' }}
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/win-setup-release/OIBus-setup-win32x64.exe
