name: publish-docker
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag to build'
        type: string
        required: true
        default: "v3.4.4"
jobs:
  publish:
    name: 'Publish OIBus to ghcr.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:build/docker"
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ github.event.inputs.tag }}
          tags: |
            ghcr.io/optimistiksas/oibus:latest
            ghcr.io/optimistiksas/oibus:${{ github.event.inputs.tag }}

