name: publish-docker
on:
  workflow_dispatch:
jobs:
  publish:
    name: 'Publish OIBus to ghcr.io'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:build/docker"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/optimistiksas/oibus:latest
            ghcr.io/optimistiksas/oibus:${{ github.ref_name }}

