name: Run DB servers 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.6
    - name: Use npm
      run: |
        npm install -g npm@7.24.1
    - name: npm install, test, lint and run db servers
      run: |
        npm ci
        npm test
        npm run lint
        npm run setup-dev-env